# Generated by Django 5.0.6 on 2024-07-07 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_distrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='distrito',
            name='nombre_distrito',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
